### ISSUE TITLE
MOD File doesn't play correctly

### ISSUE THREAD

**Issue by snakebyte69** [HeathenUK/agon_mod#3]
I realise this is an alpha release, thought this would be a good test file for you
a_nasty_disease.mod
https://modarchive.org/index.php?request=view_by_moduleid&query=88191

**Comment by HeathenUK** [comment]
This should now play correctly, if you could confirm?

**Comment by Chandler-Kluser** [comment]
there are some 4-channel mods that are being played then crashs

EDIT: realized that my vdp is not console8-vdp

sorry :sweat_smile:
