### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by gianlucarenzi** [HeathenUK/agon_mod#5]
/agon_mod\> make
[compiling] src/main.c
src/main.c:559:21: error: invalid digit '8' in octal constant
        {-12,-12,-10,-11,-08,-08,-07,-07,-06,-06,-06,-06,-06,-06,-05,-05,-04,-04,-04,-03,-03,-03,-03,-02,-03,-03,-02,-03,-03,-02,-02,-02,-02,-02,-02,-01},
                           ^
src/main.c:559:25: error: invalid digit '8' in octal constant
        {-12,-12,-10,-11,-08,-08,-07,-07,-06,-06,-06,-06,-06,-06,-05,-05,-04,-04,-04,-03,-03,-03,-03,-02,-03,-03,-02,-03,-03,-02,-02,-02,-02,-02,-02,-01},
                               ^
src/main.c:560:49: error: invalid digit '9' in octal constant
        {-18,-17,-16,-16,-13,-12,-12,-11,-10,-10,-10,-09,-09,-09,-08,-08,-07,-06,-06,-05,-05,-05,-05,-04,-05,-04,-03,-04,-04,-03,-03,-03,-03,-02,-02,-02},
                                                       ^
src/main.c:560:53: error: invalid digit '9' in octal constant
        {-18,-17,-16,-16,-13,-12,-12,-11,-10,-10,-10,-09,-09,-09,-08,-08,-07,-06,-06,-05,-05,-05,-05,-04,-05,-04,-03,-04,-04,-03,-03,-03,-03,-02,-02,-02},
                                                           ^
src/main.c:560:57: error: invalid digit '9' in octal constant
        {-18,-17,-16,-16,-13,-12,-12,-11,-10,-10,-10,-09,-09,-09,-08,-08,-07,-06,-06,-05,-05,-05,-05,-04,-05,-04,-03,-04,-04,-03,-03,-03,-03,-02,-02,-02},
                                                               ^
src/main.c:560:61: error: invalid digit '8' in octal constant
        {-18,-17,-16,-16,-13,-12,-12,-11,-10,-10,-10,-09,-09,-09,-08,-08,-07,-06,-06,-05,-05,-05,-05,-04,-05,-04,-03,-04,-04,-03,-03,-03,-03,-02,-02,-02},`

**Comment by gianlucarenzi** [comment]
some other CDev (AgDev actually) projects are compiling fine. Maybe something is missing from my setup?
Is this code usable with the AgonLight hardware with the VDP 1.4 installed?

**Comment by HeathenUK** [comment]
Sorry, this is because I'm not using a dev branch for development work and not checking compilation between commits. It should compile fine now and the source alongside Alpha 5 etc. should be compilable fine.

**Comment by gianlucarenzi** [comment]
Ok fine. I will try It ASAP

Il mer 17 gen 2024, 10:03 HeathenUK ***@***.***> ha scritto:
